### ISSUE TITLE
Can you use the gtk3 pkg-config instead of the libtool

### ISSUE THREAD

**Issue by SolarAquarion** [AyatanaIndicators/libayatana-appindicator-glib#10]

**Comment by SolarAquarion** [comment]
actually 

Package 'ayatana-indicator-0.4', required by 'virtual:world', not found

**Comment by SolarAquarion** [comment]
but that's for gtk2

**Comment by sunweaver** [comment]
@SolarAquarion We have shifted to CMake now and in CMake we use pkg-config to detect dependencies.

Note that libayatana-appindicator at the moment has two build flavours (-DFLAVOUR_GTK2=ON or -DFLAVOUR_GTK3=ON). Both build flavours have been tested thoroughly and they seem to work.
