### ISSUE TITLE
Move to cmake

### ISSUE THREAD

**Issue by mariogrip** [AyatanaIndicators/libayatana-appindicator-glib#12]
As we currently have a mix between automake and cmake, we should move to 1 build system across all projects. So lets move 100% over to cmake.

**Comment by sunweaver** [comment]
@mariogrip: When building this project, we build (and still will for a while) a GTK-2 version and a GTK-3 version. From one of the builds we grab the API doc files generated via gtk-doc. Once we switch to cmake, it would be nice allowing a GTK-2, a GTK-3 build and a doc-only build. This would reduce the build-time of the arch:all-only build that Debian's buildds do tremendously. (Mir is doing this, too, so we can learn from there cmake configuration).
