### ISSUE TITLE
.pc files lack required libraries

### ISSUE THREAD

**Issue by sunweaver** [AyatanaIndicators/libayatana-appindicator-glib#23]
The appindicator libraries requires / links against ayatana-indicator3-0.4 dbusmenu-glib-0.4 glib-2.0 gtk+-3.0. In ayatana-appindicator3-0.1.pc, only dbusmenu-glib-0.4 and gtk+-3.0 are listed.

@tari01: please fix this as part of the CMake switch PR you are currently working on. Thanks.

```
diff --git a/src/ayatana-appindicator3-0.1.pc.in b/src/ayatana-appindicator3-0.1.pc.in
index 2483ab9..064d13d 100644
--- a/src/ayatana-appindicator3-0.1.pc.in
+++ b/src/ayatana-appindicator3-0.1.pc.in
@@ -5,7 +5,7 @@ bindir=${exec_prefix}/@CMAKE_INSTALL_BINDIR@
 includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
 
 Cflags: -I${includedir}/libayatana-appindicator3-0.1
-Requires: dbusmenu-glib-0.4 gtk+-3.0
+Requires: ayatana-indicator3-0.4 dbusmenu-glib-0.4 glib-2.0 gtk+-3.0
 Libs: -L${libdir} -layatana-appindicator3
 
 Name: ayatana-appindicator3-0.1
```

**Comment by sunweaver** [comment]
in fact, there are two .pc files (one for the GTK-3 build, one for the GTK-2 build). If you keep the GTK-2 variant, please also fix things there. IMHO, we should link against libayatana-indicator (GTK-2 veriant) there. But you can also leave the complete GTK-2 backporting to me, as well.

**Comment by ghost** [comment]
> in fact, there are two .pc files (one for the GTK-3 build, one for the GTK-2 build). If you keep the GTK-2 variant, please also fix things there. IMHO, we should link against libayatana-indicator (GTK-2 veriant) there. But you can also leave the complete GTK-2 backporting to me, as well.

@sunweaver 

I have updated the GTK-3 variant only, since the resulting PR only contains that one.
