### ISSUE TITLE
Please include build instructions

### ISSUE THREAD

**Issue by Betterbird** [AyatanaIndicators/libayatana-appindicator-glib#46]
Here's what I've tried to build this:
```
git clone https://github.com/AyatanaIndicators/libayatana-appindicator
cd libayatana-appindicator
cmake .
```
At first it complained about a missing dependency `No package 'ayatana-indicator3-0.4' found` and after installing that with `sudo aptitude install libayatana-indicator3-dev` the error changes to `Requested 'ayatana-indicator3-0.4 >= 0.8.4' but version of libayatana-indicator3 is 0.6.3`.

I found the dependency a bit surprising, so I took it out. The next error then is `CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message): Could NOT find Vala (missing: VALA_COMPILER)`.

All I'd like to do is to compile the C-code in the src directory, or at least generate those four files needed to compile it:
```
#include "app-indicator-enum-types.h"
#include "application-service-marshal.h"
#include "gen-notification-watcher.xml.h"
#include "gen-notification-item.xml.h"
```
I noticed that the gen-*.xml.h were in fact generated, but the other two weren't.

**Comment by sunweaver** [comment]
This should get you the desired result:

```
mkdir ayatana-ido.pkg
cd ayatana-ido.pkg
git clone https://github.com/AyatanaIndicators/ayatana-ido
cd ayatana-ido
dpkg-buildpackage -uc -us
cd ..
dpkg -i *.deb

mkdir libayatana-indicator.pkg
cd libayatana-indicator.pkg
git clone https://github.com/AyatanaIndicators/libayatana-indicator
cd libayatana-indicator
dpkg-buildpackage -uc -us
cd ..
dpkg -i *.deb

mkdir libayatana-appindicator.pkg
cd libayatana-appindicator.pkg
git clone https://github.com/AyatanaIndicators/libayatana-appindicator
cd libayatana-appindicator
dpkg-buildpackage -uc -us
cd ..
dpkg -i *.deb
```

**Comment by Betterbird** [comment]
Wow, that wasn't all that self-explanatory, many thanks, it worked. I had do install a bunch of build dependencies (`sudo apt install gtk-sharp3-gapi libgtk3.0-cil-dev gtk-sharp2-gapi libgtk2.0-cil-dev`, just to name a subset), but it all worked in the end.
